name: Update Additives Database

on:
  # schedule:
  #   - cron: '0 0 1 * *' # Monthly
  workflow_dispatch:    # Manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run update script
        run: bun run ./scripts/update-additives.ts

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code src/lib/data/additives-min.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and Push
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/lib/data/additives-min.json
          git commit -m "chore: update additives database [skip ci]"
          git push
